
#Modify chances of natural Heavily Infected Spawns. Higher values means higher spawn rates
["Spawn Weights"]
	#Changes natural spawn weight of infected Divers
	#Range: 0 ~ 1000
	infectedDiverSpawn = 5
	#Changes natural spawn weight of infected Villagers
	#Range: 0 ~ 1000
	infectedVillagerSpawn = 1
	#Changes natural spawn weight of infected Humans
	#Range: 0 ~ 1000
	infectedHumanSpawn = 5

#Modify game mechanics based on dimensions
[cleansedDimensions]
	#EXPERIMENTAL! MUST BE ALL CHARACTERS FROM [a-z0-9/._-] OR THE GAME WILL CRASH. List the dimension names that you want the following configs to interact with. (e.g. the_bumblezone:the_bumblezone,minecraft:overworld
	infectionDimensionCleanse = "notadimension"
	#Disables raw food infections in cleansed dimensions
	rawFoodInfectedInCleanse = true
	#Disables hostile mob attack based infections in cleansed dimensions
	hostileInfectInCleanse = true
	#Disables player attack based infections in cleansed dimensions
	playerInfectInCleanse = false
	#Disables hostile mob aerosol infections in cleansed dimensions
	hostileAerosolInCleanse = true

